#!/bin/bash

# Add the respective package name to the files auto-generated by antlr4
sed -i '1s/^/package com.peerisland.parser.generated;\n\n/' ./src/main/java/com/peerisland/parser/generated/Calculator*.java
